Q61. Write a program to return the mean value of a tuple of tuples.

In [1]:
t=((1,2),(3,4))

In [30]:
def mean_tuple(numbers):
    result = [sum(x) / len(x) for x in zip(*numbers)]
    return result

In [32]:
# Q62. What is the use of self in Python?

In [36]:
# self keyword-used to access current instance of a class,using self we can access class attributes

In [37]:
# Q63. What are the different types of variables in Python OOP?

In [3]:
import numpy as np

In [44]:
a=np.array([[1,2,3,4,5],
           [6,7,8,9,10]]
          )


In [50]:
a[:,[0]]

array([[1],
       [6]])

In [51]:
# Q68. How can we check for an array with only zeros?

In [52]:
b=np.array([0,0,0,0,0,0])

In [56]:
np.size(b)

6

In [57]:
# Q69. How can we concatenate two arrays?

In [4]:
a=np.array([[1,2,3],[6,7,8]])

b=np.array([[4,5,6],[1,2,3]])

In [70]:
np.concatenate((a,b),axis=0)

array([[1, 2, 3],
       [6, 7, 8],
       [4, 5, 6],
       [1, 2, 3]])

In [75]:
c = np.array(["hello", "world", "python"])

In [76]:
np.char.join(",",c)

array(['h,e,l,l,o', 'w,o,r,l,d', 'p,y,t,h,o,n'], dtype='<U11')

In [1]:
a

NameError: name 'a' is not defined

In [14]:
New_arr = np.pad(a, pad_width=2, mode='constant', 
constant_values=1)

In [15]:
New_arr

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 2, 3, 1, 1],
       [1, 1, 6, 7, 8, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [7]:
a

array([[1, 2, 3],
       [6, 7, 8]])

In [18]:
a

array([[1, 2, 3],
       [6, 7, 8]])

In [21]:
np.swapaxes(a,0,1)

array([[1, 6],
       [2, 7],
       [3, 8]])

In [22]:
# Q75. How to get the indices of n maximum values in a given array?

In [23]:
import pandas as pd

In [49]:
d={'col1': [10, 0], 'col2': [10, 4]}

In [50]:
df=pd.DataFrame(d)

In [48]:
df["col1"].astype(int)

0    1
1    0
Name: col1, dtype: int32

In [54]:
df

col1  col2
0    10    10
1     0     4

In [ ]:
# df.loc -used to access data based on its labels of rows and its columns
# df.iloc used to access data based on its numerical postions

In [56]:
df.loc[0,"col1"]

10

In [66]:
df.iloc[1]

col1    0
col2    4
Name: 1, dtype: int64

In [67]:
df

col1  col2
0    10    10
1     0     4

In [68]:
# Q79. How do you sort a dataframe by two columns?

In [71]:
df.sort_values(by=["col2"])

col1  col2
1     0     4
0    10    10

In [72]:
# Q80. Find the row which has the maximum value of a given column.

In [73]:
df

col1  col2
0    10    10
1     0     4

In [77]:
# df["col1"].idxmax() '''it returns the index which has highest value'''

In [78]:
# Q81. How can you split a column which contains strings into multiple columns?

In [83]:
df["col3"]=["shan,mani","mani,shan"]

In [84]:
df

col1  col2       col3
0    10    10  shan,mani
1     0     4  mani,shan

In [88]:
df["col3"].str.split(pat="")

0    [, s, h, a, n, ,, m, a, n, i, ]
1    [, m, a, n, i, ,, s, h, a, n, ]
Name: col3, dtype: object

In [86]:
df

col1  col2       col3
0    10    10  shan,mani
1     0     4  mani,shan

In [90]:
# Q82. What is the difference between map() and applymap()?

In [89]:
# map-for series element wise operation
# applymanp -for dataframes element wise operations

In [96]:
df.drop('col3',axis=1,inplace=True)

In [97]:
df.pct_change(periods=1)

col1  col2
0   NaN   NaN
1  -1.0  -0.6